force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BK-2026-{000}</displayFormat>
        <label>Booking NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked-in</fullName>
            </value>
            <value>
                <fullName>Checked-out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <label>Check-in Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Check_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_Date__c</fullName>
    <label>Check-out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <label>Number of Guests</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>S-{00}</displayFormat>
        <label>SN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Guest__c.field-meta.xml
<CustomField>
    <fullName>Guest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Price_Per_Night__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Night__c</fullName>
    <label>Price Per Night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Deluxe</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stay_Booking__c/Stay_Booking__c.object-meta.xml
<CustomObject>
    <label>Stay Payment</label>
    <nameField>
        <displayFormat>HE-{00}</displayFormat>
        <label>Stay Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stay Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay_Booking__c/fields/No_of_day_Stay__c.field-meta.xml
<CustomField>
    <fullName>No_of_day_Stay__c</fullName>
    <label>No of day Stay</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay_Booking__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Stay Payments</relationshipLabel>
    <relationshipName>Stay_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HotelRoomController.cls
public with sharing class HotelRoomController {

    @AuraEnabled(cacheable=true)
    public static List<Room__c> getRooms(Id hotelId) {
        return [
            SELECT Id, Room_Number__c, Room_Type__c, Price_Per_Night__c,
                   Status__c, Hotel__c, Guest__c
            FROM Room__c
            WHERE Hotel__c = :hotelId
            ORDER BY Room_Number__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Room__c> getAvailableRooms(Id hotelId) {
        return [
            SELECT Id, Room_Number__c, Room_Type__c, Price_Per_Night__c,
                   Status__c, Hotel__c, Guest__c
            FROM Room__c
            WHERE Hotel__c = :hotelId
            AND Status__c = 'Available'
            ORDER BY Room_Number__c
        ];
    }

    // ============================
    // MAIN CHECK-IN FLOW (FINAL)
    // ============================
   @AuraEnabled
public static Id processCheckIn(
    String guestName,
    String email,
    String phone,
    Integer numberOfGuests,
    Date checkInDate,
    Date checkOutDate,
    Id roomId,
    Decimal pricePerNight,
    Integer numberOfDays
) {

    System.debug('=== CHECK-IN START ===');
    System.debug('Guest: ' + guestName);
    System.debug('RoomId: ' + roomId);
    System.debug('Days: ' + numberOfDays);

    try {

        // 1. CREATE CONTACT
        Contact c = new Contact(
            LastName = guestName,
            Email = email,
            Phone = phone
        );
        insert c;

        System.debug('Contact Created: ' + c.Id);

        // 2. CREATE BOOKING
        Booking__c b = new Booking__c(
            Check_in_Date__c = checkInDate,
            Check_out_Date__c = checkOutDate,
            Number_of_Guests__c = String.valueOf(numberOfGuests), // ✅ FIX
            Booking_Status__c = 'Confirmed',
            Room__c = roomId
        );
        insert b;

        System.debug('Booking Created: ' + b.Id);

        // 3. CREATE STAY BOOKING
        Stay_Booking__c s = new Stay_Booking__c(
            Room__c = roomId,
            No_of_day_Stay__c = String.valueOf(numberOfDays), // ✅ FIX
            Total_Price__c = pricePerNight * numberOfDays
        );
        insert s;

        System.debug('Stay Booking Created: ' + s.Id);

        // 4. UPDATE ROOM
        Room__c r = new Room__c(
            Id = roomId,
            Status__c = 'Occupied',
            Guest__c = c.Id
        );
        update r;

        System.debug('Room Updated');
        System.debug('=== CHECK-IN SUCCESS ===');

        return b.Id;

    } catch (Exception e) {

        System.debug('ERROR: ' + e.getMessage());
        System.debug('STACK: ' + e.getStackTraceString());

        throw new AuraHandledException('Check-in failed: ' + e.getMessage());
    }
}
}