force-app/main/default/objects/Token__c/Token__c.object-meta.xml
<CustomObject>
    <label>Token</label>
    <nameField>
        <displayFormat>T-{00}</displayFormat>
        <label>Token Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Token__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counter</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tokens</relationshipLabel>
    <relationshipName>Tokens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TokenVFController.cls
public with sharing class TokenVFController {

    public Token__c token { get; set; }
    public String currentTime { get; set; }

    public TokenVFController() {

        Id tokenId = ApexPages.currentPage().getParameters().get('id');

        token = [
            SELECT Id, Token_Number__c,
                   Counter__r.Name,
                   Counter__r.Counter_Number__c
            FROM Token__c
            WHERE Id = :tokenId
        ];

        currentTime = System.now().format('dd/MM/yyyy hh:mm a');
    }
}